language: node_js
node_js:
- lts/*
cache: npm
repos:
  RebusFoundation/reader-api:
    endpoint: https://api.travis-ci.org/
addons:
  postgresql: '9.4'
services:
- postgresql
before_install:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_28143c166499_key
  -iv $encrypted_28143c166499_iv -in secrets.tar.enc -out secrets.tar -d || true'
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && tar xvf secrets.tar || true'
- psql -c 'create database travis_ci_test;' -U postgres
